### ISSUE TITLE
Ignore kubectl command's flags that stream input or output 

### ISSUE THREAD

**Issue by dgil** [harbur/kubebot#1]
Running `!kubectl logs -f pod-id` hangs the kubebot.

Kubebot should not run commands that stream results. Proposal list:

* `get`
    * `-f`
    * `--filename`
    * `-w`
    * `--watch`
    * `--watch-only`
* `describe`
    * `-f`
    * `--filename`
* `create`
    * `-f`
    * `--filename`
* `replace`
    * `-f`
    * `--filename`
* `patch`
    * `-f`
    * `--filename`
* `delete`
    * `-f`
    * `--filename`
* `edit`
    * `-f`
    * `--filename`
* `apply`
    * `-f`
    * `--filename`
* `namespace`
    * _nothing_
* `logs`
    * `-f`
    * `--follow`
* `rolling-update`
    * `-f`
    * `--filename`
* `scale`
    * `-f`
    * `--filename`
* `cordon`
    * _nothing_
* `drain`
    * _nothing_
* `uncordon`
    * _nothing_
* `attach`
    * `-i`
    * `--stdin`
    * `-t`
    * `--tty`
* `exec`
    * `-i`
    * `--stdin`
    * `-t`
    * `--tty`
* `port-forward`
    * _nothing_
* `proxy`
    * _nothing_
* `run`
    * `--leave-stdin-open`
    * `-i`
    * `--stdin`
    * `--tty`
* `expose`
    * `-f`
    * `--filename`
* `autoscale`
    * `-f`
    * `--filename`
* `rollout`
    * _nothing_
* `label`
    * `-f`
    * `--filename`
* `annotate`
    * `-f`
    * `--filename`
* `config`
    * _nothing_
* `cluster-info`
    * _nothing_
* `api-versions`
    * _nothing_
* `version`
    * _nothing_
* `explain`
    * _nothing_
* `convert`
    * `-f`
    * `--filename`

**Comment by dgil** [comment]
I've updated the list with all the supported commands of `kubectl` (`v1.2.4`) and the ignored flags for each of them. 

@spiddy do you find anything missing?

**Comment by spiddy** [comment]
Looks good!
