### ISSUE TITLE
Whitelist kubectl commands

### ISSUE THREAD

**Issue by dgil** [harbur/kubebot#4]
We want to improve the security of Kubebot and the next step is implement a whitelist of commands that Kubebot can run. This makes easy to setup a Kubebot in "read mode", "custom access" or "full access".

The implementation should make it easy to setup which commands can run Kubebot. In order to make it consistent with the current implementation I suggest using a env variable. 

Proposal:
```
KUBEBOT_SLACK_VALID_COMMANDS="get describe logs explain" 
```

**Comment by spiddy** [comment]
Proposal ACK
